XRTK-Core Release v0.2.1
XRTK/XRTK-Core pull request #756
Opened 2021-01-14 23:03 UTC by FejZa

# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Patch release for the core module containing the adjusted Editor assembly and build tools location.

## Changes

- Build Tools and Editor Utilities now all located in the root /Editor assembly

## Breaking Changes

- Build Tools have moved location from `/Runtime/Utilities/Editor` to `/Editor/BuildAndDeploy/`

2021-01-14 23:35 UTC, StephenHodgson approved these changes

2021-01-14 23:41 UTC, StephenHodgson requested changes
Lets fix the NREs in the build

2021-01-15 00:57 UTC, SimonDarksideJ commented
There seem to be way too many changes in this PR that I would expect.  Also, the .github files seem to be getting removed?
Might need a good going over to understand why there are so many changes when we've only updated a few things since .2

2021-01-15 00:58 UTC, StephenHodgson commented
All the changes are cumulative from what we've done so far. 

Most of the changes are from the docs. 

the removal of the .github folder is bc it was a duplicate.

2021-01-15 00:59 UTC, StephenHodgson approved these changes

2021-01-15 01:09 UTC, merged